Create markup directory
htmlacademy-yii/1530283-task-force-2 pull request #2
Opened 2022-07-24 12:00 UTC by nadProg

2022-07-30 21:16 UTC, sergeivl commented on classes/task.php
> +<?php
1) В рамках текущего задания нужно сделать только один класс - класс Task. Остальные классы следует пока удалить
2) Нужно следовать стандарту - имя класса должно совпадать с именем файла - в том числе и регистр. То есть имя файла должно быть `Task.php`

2022-07-30 21:22 UTC, sergeivl commented on classes/task.php
> +    private Contractor|null $contractor;
Класс Task по сути являются моделью таблицы в базе данных, а свойства класса должны соответствовать столбцам в БД.
Следует добавить столбцы с идентификаторами:
customer_id - целочисленный идентификатор заказчика
contractor_id  - целочисленный идентификатор исполнителя

2022-07-30 21:23 UTC, sergeivl commented on classes/task.php
> +        Contractor $contractor = null,
привести изменения в соответствие с прошлым моим комментарием

2022-07-30 21:25 UTC, sergeivl reviewed
Сделать правки по комментариям к коду

2022-07-31 05:01 UTC, nadProg commented on classes/task.php
> +<?php
@sergeivl  Можно ли оставить классы с константами `TaskStatus` и `TaskAction` ?

2022-08-02 09:11 UTC, b1rdex requested changes
Нужно немного доработать

2022-08-02 09:11 UTC, b1rdex commented on classes/Task.php
> +                return $this->status === TaskStatus::NEW ? $this->status
Кажется тут должен быть переход в in progress

2022-08-02 09:11 UTC, b1rdex commented on classes/Task.php
> +    public function getCustomerAction(): ?string
1) Это нужно объединить с getContactorAction и добавить аргумент - id пользователя, который совершает действие. А внутри метода уже сравнивать и определять кто запрашивает и возвращать доступные действия. 
2) Возвращаемый тип нужно сделать массивом, так как там есть состояния с несколькими доступными действиями

2022-08-02 10:14 UTC, nadProg commented on classes/Task.php
> +                return $this->status === TaskStatus::NEW ? $this->status
Насколько я понимаю - нет. Т.к. при отклике создается новая сущность - отклик. И уже после принятия новой сущности - привязанная к отклику задача переходит в `In Progress`. + откликаться должны иметь возможность разные исполнители - так сформируются разные отклики, из которых заказчик будет выбирать.

2022-08-02 10:19 UTC, nadProg commented on classes/Task.php
> +    public function getCustomerAction(): ?string
Объединю методы, сделаю возврат массивом. 
Но согласно текщему ТЗ доступное действие будет либо 1, либо его не будет, т.е. массив будет состоять либо из одного элемента, либо пустой.
Однако при возврате массива есть преимущество, что список доступных действий может быть расширен легко при необходимости.

Из ТЗ видно, что для конкретной роли, при либо статусе - не более одного доступного дейтствия. Или я не правильно понимаю ТЗ?
![Screenshot_314](https://user-images.githubusercontent.com/63777417/182351790-91b6b036-80e1-43bd-8e42-d9f8b6d01083.png)

2022-08-02 10:22 UTC, nadProg reviewed
Ответил на замечания

2022-08-03 04:55 UTC, b1rdex commented on classes/Task.php
> +    public function getCustomerAction(): ?string
Да, видимо я что-то перепутал

2022-08-03 04:55 UTC, b1rdex approved these changes

2022-08-03 04:55 UTC, merged